import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/NavBar'
import JoinUsAndFooter from '@/components/JoinUsAndFooter'
import { NavBar } from '@/components/component/nav-bar'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}
        <JoinUsAndFooter/>
        <Script id="sslczPayBtn">
          {`
            (function (window, document) {
              var loader = function () {
                var script = document.createElement("script"), tag = document.getElementsByTagName("script")[0];
                script.src = "https://sandbox.sslcommerz.com/embed.min.js?" + Math.random().toString(36).substring(7);
                tag.parentNode.insertBefore(script, tag);
              };
              window.addEventListener ? window.addEventListener("load", loader, false) : window.attachEvent("onload", loader);
            })(window, document);
          `}
        </Script>
        </body>
    </html>
  )
}
